global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using Soneta.Business;
global using Soneta.Business.UI;
global using Soneta.CRM;
global using Soneta.Handel;
global using Soneta.Tools;
global using Soneta.Types;
global using UstawianieKuriera;
global using env = System.Environment;
